// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - start a thread-scoped realtime session.
 */
export type ThreadRealtimeStartParams = { threadId: string, prompt: string, sessionId?: string | null, };
